language: groovy

sudo: false
# addons:
#   apt:
#     packages:
#       - oracle-java8-installer

jdk:
  - oraclejdk8

install: true

before_script:
  - cd ..
  - git clone https://github.com/moqui/moqui-framework.git moqui
  - cd moqui
  - chmod +x gradlew

env:
  - TERM=dumb

script:
  - ./gradlew getGit -Pcomponent=mantle-usl
  - ./gradlew load
  - ./gradlew runtime/component/mantle-usl:test --info

cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper
