language: groovy

sudo: false

jdk:
  - oraclejdk8

install: true

before_script:
  - cd ..
  - git clone https://github.com/moqui/moqui-framework.git moqui
  - cd moqui
  - chmod +x gradlew

env:
  - TERM=dumb

script:
  - ./gradlew getGit -Pcomponent=HiveMind
  - ./gradlew load
  - ./gradlew runtime/component/HiveMind:test

cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper
